option(
  'profile',
  type: 'combo',
  choices: [
    'release',
    'dev'
  ],
  value: 'release',
  description: 'The build profile for Resources. One of "dev" or "release".'
)
option(
  'development_build',
  type: 'boolean',
  value: false,
  description: 'Enables visual development build hints and git version information.'
)
