[package]
name = "process-data"
version = "51.0.0-beta"
edition = "2024"
rust-version = "1.93.0"
homepage = "https://apps.gnome.org/app/org.gnome.Resources/"
license = "GPL-3.0-or-later"

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = true
strip = true
opt-level = 3

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.4", features = ["derive"], optional = true }
lazy-regex = "3.6.1"
libc = "0.2.189"
log = "0.4.33"
num_cpus = "1.17.0"
nutype = { version = "0.7.0", features = ["serde"] }
nvml-wrapper = "0.12.1"
serde = { version = "1.0.229", features = ["serde_derive"] }
serde_json = "1.0"
thiserror = "2.0.19"
unescape = "0.1.0"
uzers = "0.12.2"

[dev-dependencies]
pretty_assertions = "1.4.1"

[features]
cli = ["dep:clap"]